# Generated by Django 5.0.1 on 2024-01-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_owner_alter_contact_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='creat_date',
            new_name='created_date',
        ),
    ]
