# Generated by Django 5.0.1 on 2024-09-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_creat_date_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='personality',
            field=models.TextField(blank=True),
        ),
    ]
